### ISSUE TITLE
Build failed: No rule to make target '/usr/lib/libboost_regex.so.1.79.0'

### ISSUE THREAD

**Issue by petronny** [ros-noetic-arch/ros-noetic-cv-bridge#1]
```
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_nodejs
make[2]: *** No rule to make target '/usr/lib/libboost_regex.so.1.79.0', needed by 'devel/lib/libcv_bridge.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 16%] Building CXX object src/CMakeFiles/cv_bridge.dir/cv_bridge.cpp.o
[ 33%] Building CXX object src/CMakeFiles/cv_bridge.dir/rgb_colors.cpp.o
make[1]: *** [CMakeFiles/Makefile2:846: src/CMakeFiles/cv_bridge.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
```
https://github.com/arch4edu/cactus/actions/runs/3208848659/jobs/5245076797

**Comment by lprobsth** [comment]
I'm still in the process of debugging this... my current bet is that the cv-bridge links to the binaries of other already built ros packages that depend on boost. Since boost was updated in the meantime these links are broken since they target boost 1.79 and the shared library files of this version don't exist anymore...

So probably rebuilding / reinstalling all ros packages is the right way.

Shouldn't pacman or the aur helpers detect that there are packages that depend on another rebuilt package and build them as well?

**Comment by lprobsth** [comment]
Relevant comment:
https://github.com/Jguer/yay/issues/1269#issuecomment-656560770

**Comment by lprobsth** [comment]
Also relevant:
https://github.com/Morganamilo/paru/issues/744

**Comment by petronny** [comment]
Alright, I'll first try rebuild 27 packages which directly depend on boost.

**Comment by petronny** [comment]
Rebuilding packages which directly depend on boost fixed the issue for this package. I think this issue can be closed.

However, rebuilding these packages won't fix the same error for ros-noetic-rosbag. https://github.com/ros-noetic-arch/ros-noetic-rosbag/issues/3
